# Generated by Django 2.2.5 on 2019-10-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfiction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dark',
            field=models.BooleanField(default=True),
        ),
    ]
