# Generated by Django 2.2.5 on 2019-10-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfiction', '0002_user_is_dark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_dark',
            field=models.BooleanField(default=False),
        ),
    ]
